### ISSUE TITLE
headerOrder should take a Proxy

### ISSUE THREAD

**Issue by ivan-m** [hvr/cassava#138]
Currently, the `DefaultOrdered` class' method `headerOrder` takes an argument whose value isn't used, just the type.  Shouldn't a `Proxy` be used instead?

(This will, however, be a breaking change.)

**Comment by hvr** [comment]
I agree this would be more principled, but I'm hesitant at this point. I'll think about this...

**Comment by ivan-m** [comment]
Sure; this is a "if you're going to be making breaking changes _anyway_ ..." issue.

**Comment by ivan-m** [comment]
How about if nothing else changing the generic definitions, since they're not exported?

**Comment by hvr** [comment]
@ivan-m can you make a PR to show what you mean? cleaning up internals if they don't leak into the API sounds good to me; assuming they have no measurable performance regression

**Comment by ivan-m** [comment]
Nevermind, `selName` takes a value and hence requires `undefined`, so we'd be converting to `Proxy` just to convert back to `undefined`.

**Comment by ivan-m** [comment]
I'm going to close this until/unless `selName` in `GHC.Generics` uses `Proxy` rather than `undefined`.

**Comment by mbwgh** [comment]
I actually just triggered `Prelude.undefined` because of this, by accidentally writing an instance like

```haskell
instance DefaultOrdered Student where
  headerOrder Student{..} = header [...]
```

In hindsight, I should have noticed the unused variable, but I was just writing a hackish script.
I believe the haddocks could be more clear about this. Currently, they only refer to how to *call* this function, but not to the caveats that may arise when implementing it.
